# Generated by Django 5.2.3 on 2025-07-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kmal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='address',
            new_name='subject',
        ),
    ]
